name: MediaLog
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.9.0
  go_router: ^17.0.1
  json_annotation: ^4.9.0
  google_fonts: ^8.0.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.6.1
  json_serializable: ^6.7.1
flutter:

  uses-material-design: true
  assets:
    - .env

